Pix 38 Service workers
AIVorozhtcov/PixelWizards pull request #11
Opened 2024-08-08 16:25 UTC by ZuevaDarya

Подключила service worker по стратегии network-first: работаем по сети и кладем данные в кеш, если сеть пропадает - делаем запросы в кеш.

2024-08-08 19:56 UTC, mikhailKhmel commented
packages/client/cacheServiceWorker.js
почему js, а не ts ?

2024-08-09 16:19 UTC, ZuevaDarya commented
Там данные из вне не прокидываются и типы по сути не используются, поэтому решила, что будет js, в принципе, если смущает, могу и на ts переписать (еще надо будет конфиги понастраивать), только особо большого смысла в этом не вижу.
Ну и на просторах интернета посмотрела - большинство на js пишут и в React проектах и в прочих.

2024-08-09 23:03 UTC, AIVorozhtcov approved these changes

2024-08-10 01:13 UTC, kyzinatra commented on packages/client/cacheServiceWorker.js
> +  '/index.html',
Надо исправить: сейчас вы кэшируете 2 одинаковых файла, так как `/` и `/index.html` выдает одно и тоже. При этом вы не кэшируете картинки и скрипты в `install`. Они хоть и могут кэшироваться через `fetch`, но лучше так не делать и работать с этими ресурсами как есть. 
Стоит прописать пути до всех ресурсов, чтобы их кэшировать

2024-08-10 01:13 UTC, kyzinatra commented on packages/client/cacheServiceWorker.js
> +          .open(CACHE_NAME)
Хорошее кэширование запросов

2024-08-10 01:14 UTC, kyzinatra requested changes
Отличная работа над сервис воркером, но сейчас вы кэшируете 2 одинаковых файла, так как / и /index.html выдает одно и тоже. При этом вы не кэшируете картинки и скрипты в install. Они хоть и могут кэшироваться через fetch, но лучше так не делать и работать с этими ресурсами как есть. Стоит прописать пути до всех ресурсов, чтобы их кэшировать, после этого отправьте работу снова и она будет принята!

2024-08-10 10:02 UTC, ZuevaDarya commented on packages/client/cacheServiceWorker.js
> +  '/index.html',
Нужно ли кэшировать сразу, например, компоненты страниц Login.tsx, Profile.tsx и т.п.?

2024-08-10 11:16 UTC, kyzinatra commented on packages/client/cacheServiceWorker.js
> +  '/index.html',
Вы не сможете их кэшировать так как они не входят в итоговый бандл. Вам нужно кэшировать только то. Что в него входит. То есть .is, . css  файлы и картинки

2024-08-10 11:36 UTC, ZuevaDarya commented on packages/client/cacheServiceWorker.js
> +  '/index.html',
Спасибо!

2024-08-10 16:01 UTC, ZuevaDarya commented on packages/client/cacheServiceWorker.js
> +  '/index.html',
Возник еще один вопрос. После сборки бандла React добавляет в названии файлов хэши. 

![image](https://github.com/user-attachments/assets/2d6000d2-0e7d-4848-839b-43f7cf93c528)

Как в этом случае правильно кэшировать эти файлы? Автоматизировать получение файлов в папке assets, например, используя модуль fs, на клиенте нельзя, серверной части пока нет. Т.е. остается только вручную прописывать файлы с хэшами?

2024-08-10 22:41 UTC, ZuevaDarya commented on packages/client/cacheServiceWorker.js
> +  '/index.html',
Вроде решила вопрос

2024-08-10 23:32 UTC, kyzinatra commented on packages/client/public/updateServiceWorker.cjs
> +
Да, хорошее решение. Есть еще библиотеки в npm, которые помогают работать с PWA. Там в том числе есть и такие функции

2024-08-10 23:32 UTC, kyzinatra approved these changes
Да, хорошее решение. Есть еще библиотеки в npm, которые помогают работать с PWA. Там в том числе есть и такие функции

2024-08-11 11:25 UTC, merged